### ISSUE TITLE
Singletons

### ISSUE THREAD

**Issue by pography** [fikaproductions/fika-gatsby-source-cockpit#4]
Are there any plans to support Singletons?

Creating one as a collection works for now but it would be useful to support this feature.

**Comment by WhippetsAintDogs** [comment]
Yes, I plan to implement them soon if @davesouthey who forked the project in order to contribute (https://github.com/conical-io/fika-gatsby-source-cockpit) doesn't come through.

**Comment by davesouthey** [comment]
I'm facing some issues trying to achieve what I need due to the limited information provided by cockpit on a singleton request. Currently, it doesn't provide any field information, which makes handling the various field types difficult. My fork currently works for text fields using something like cockpitSingleton(name: { eq: "social" }) but I don't yet have a solution for other field types. 

I am considering building a custom singleton module for cockpit which provides the data in a format more like collections, including all the field information.

Maybe there is a simpler solution?

**Comment by WhippetsAintDogs** [comment]
Ok, well that's a bummer. I tought that the APIs would have been the same. I'll think about it. I really wish that a Cockpit plugin won't be the solution and that we will make this works with any vanilla Cockpit setups.

**Comment by WhippetsAintDogs** [comment]
Great news, it seems that since Cockpit version 0.7.2, we can now access the Singleton's schema with the /api/singletons/singleton/{singletonname} endpoint (https://github.com/agentejo/cockpit/issues/856). @davesouthey, do you want to complete your fork with the fix ? Otherwise, I'll implement it :)

**Comment by davesouthey** [comment]
@WhippetsAintDogs that is great news! I'm not going to have time to complete it at the moment so feel free to implement it if you have time. Thanks

**Comment by WhippetsAintDogs** [comment]
All right ! :+1:

**Comment by WhippetsAintDogs** [comment]
Support for Singletons added in version 1.1.0+. Closing this issue.
